apiVersion: batch/v1
kind: Job
metadata:
  name: during-wave-2
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "2"
spec:
  template:
    spec:
      containers:
      - name: sleep
        image: alpine:latest
        command: ["sleep", "3"]
      restartPolicy: Never
  backoffLimit: 0
